routes/web.php
<?php

use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

//  Route::get('/invoice', function() {

//     $pdf = PDF::loadView('pdf.invoice', $data);
//     return $pdf->download('invoice.pdf');

//     // return view('components.invoice');
//  });

// Route::get('/email', function() {
//     Mail::to('keygames@eshop.com')->send(new WelcomeMail());

//     return new WelcomeMail();
// });

Route::get('/', 'HomeController@public');
Route::get('/shop', 'HomeController@public')->name('shop.index');
Route::get('/shop/{product}', 'HomeController@show')->name('shop.show');

Route::get('/login', 'LoginController@public');
Route::get('/myaccount', 'LoginController@account');
Route::get('/search', 'SearchController@search')->name('search');

Auth::routes();
Route::middleware('auth')->group(function () {
    Route::get('/members', 'MemberController@index');
    Route::get('/members/edit', 'MemberController@edit')->name('member.edit');
    Route::get('/cart', 'CartController@public');
    Route::patch('/cart/{product}', 'CartController@update')->name('cart.update');
    Route::delete('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
    Route::get('empty', function () {
        Cart::destroy();
    });
    Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
    Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');
    Route::post('/coupon', 'CouponController@store')->name('coupon.store');
    Route::delete('/coupon', 'CouponController@destroy')->name('coupon.destroy');
    Route::get('/thankyou', 'ConfirmationController@index')->name('confirmation.index');
    Route::post('/coupon', 'CouponController@store')->name('coupon.store');
    Route::delete('/coupon', 'CouponController@destroy')->name('coupon.destroy');
    Route::get('/my-orders', 'OrdersController@index')->name('orders.index');
    Route::get('/my-orders/{order}', 'OrdersController@show')->name('orders.show');

    Route::resources([
        'members' => 'MemberController',
        '/cart' => 'CartController',
        'memberList' => 'MemberListController',
    ]);
    Route::middleware('admin')->group(function () {
        Route::get('/admin', 'AdminController@index');
        Route::get('admin/gamelist', 'AdminController@gamelist')->name('product.index');
        Route::post('admin/gamelist', 'ProductController@create')->name('product.create');
        Route::post('admin/gamelist', 'ProductController@edit')->name('product.edit');
        Route::post('admin/gamelist', 'ProductController@destroy')->name('product.destroy');
        Route::get('admin/memberList', 'AdminController@memberList')->name('member.index');
        Route::post('admin/memberList', 'MemberListController@edit')->name('memberList.edit');
        Route::post('admin/memberList', 'MemberListController@destroy')->name('memberList.destroy');

        Route::resources([
            'admin' => 'AdminController',
            'admin/product' => 'ProductController',
            'admin/member' => 'MemberController',
            'admin/memberList' => 'MemberListController',
        ]);
    });
});
Route::get('/home', 'HomeController@register')->name('home');

Route::get('/mailable', function () {
    $order = App\Order::find(1);

    return new App\Mail\OrderPlaced($order);
});

Route::get('/invoice/{id}', 'OrdersController@getPdf')->name('getPdf');
// Route::get('invoice', function () {
//     $pdf = PDF::loadview('invoice/invoice');
//     return $pdf->download('invoice.pdf');
// });

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  {{-- <title>{{ config('app.name', 'Laravel') }}</title> --}}
  <title>Keygames - Login</title>

  <!-- Scripts -->
  <script src="{{ asset('js/app.js') }}" defer></script>

  <!-- Fonts -->
  <link rel="dns-prefetch" href="//fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body style="background-color:rgb(53, 54, 58); margin:0 auto">
  <div id="app">
    <nav class="navbar navbar-expand-md navbar-light shadow-sm"
      style="background-image: linear-gradient(135deg, #667eea 0%, #764ba2 100%);">
      <div class="container">
        <a class="navbar-brand mt-2 text-center d-flex" style="align-items: center; 
        color:rgba(255, 173, 10, 1);
        font-size:30px;
        font-family:Arial, Helvetica, sans-serif"
         href="{{ url('/') }}">
          {{-- {{ config('app.name', 'Laravel') }} --}}
          <img src="/img/logo.png" width="40px" height="38px" class="d-inline-block align-top"
            style=" border-radius:50%;" alt=""> 
          <b>
            <i>KEYGAMES</i>
          </b>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left Side Of Navbar -->
          <ul class="navbar-nav mr-auto">

          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
            <li class="nav-item">
              <a class="nav-link text-white" href="{{ route('login') }}">Connexion</a>
            </li>
            @if (Route::has('register'))
            <li class="nav-item">
              <a class="nav-link text-white" href="{{ route('register') }}">Inscription</a>
            </li>
            @endif
            @else
            <li class="nav-item dropdown">
              <a id="navbarDropdown" class="nav-link dropdown-toggle text-white" href="#" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }} <span class="caret"></span>
              </a>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                  {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
                </form>
              </div>
            </li>
            @endguest
          </ul>
        </div>
      </div>
    </nav>

    <main class="mt-5">
      @yield('content')
    </main>
  </div>
</body>

</html>

resources/views/layouts/template.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
    <link href="{{ asset('css/mobile.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css"
        integrity="sha384-REHJTs1r2ErKBuJB0fCK99gCYsVjwxHrSU0N7I1zl9vZbggVJXRMsv/sLlOAGb4M" crossorigin="anonymous">

    <!----This link is for the stars rating...--->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <title>@yield('title')</title>
</head>

<body>
    <header class="navbar navbar-light">
        <a class="navbar-brand" href="/">
            <img src="/img/logo.png" width="75" height="70" class="d-inline-block align-top" alt="">
            <i>KEYGAMES</i>
        </a>


        <form action="{{route('search')}}" method="GET" class="form-inline">
            <input class="form-control mr-sm-2" type="text" name="query" id="query"
                value="{{ request()->input('query') }}" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="icon-home">
                <a href="/" class="item"><i class="fas fa-home"></i></a>
            </div>
            <ul class="navbar-nav pl-0">
                @foreach ($categories as $category)
                <li class="nav-item">

                    <a class="nav-item nav-link text-white"
                        href="{{ route('shop.index', ['category' => $category->id ])}}"><span>{{ $category->name }}</span></a>
                </li>
                @endforeach
            </ul>
        </div>

        <div class="connect">
            @if(Auth::check())
            <div class="account-item">
                <div class="btn-group">
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        {{ Auth::user()->lastname }}
                        {{ Auth::user()->name }}
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item text-dark" href="{{route('members.index')}}">Mon profil</a>
                        @if (Auth::user()->is_admin == 0)
                        <a class="dropdown-item text-dark" href="{{route('orders.index')}}">Mes commandes</a>
                        @elseif (Auth::user()->is_admin == 1)
                        <a class="dropdown-item text-dark" href="{{route('admin.index')}}">Mon dashboard</a>
                        @endif
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item text-dark" href="{{ route('logout') }}" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </div>
            </div>
            @if (Auth::user()->is_admin == 0)
            <div class="cart-nav">
                <a href="{{ route('cart.index') }}" class="nav-item nav-link text-white">
                    <i class="fas fa-shopping-cart"></i>

                    @if (Cart::instance('default')->count() > 0)
                    <span class="cart-count"><span>{{ Cart::instance('default')->count() }}</span></span>
                    @endif
                </a>
            </div>
            @endif


            @else
            <a class="nav-item nav-link " href="/login">Connexion <i class="fas fa-user-circle"></i></a>
        </div>

        @endif

    </nav>


    <div class="box">
        <div class="jumbotron bg-light">
            @yield('content')

        </div>
    </div>

    <footer>
        <div class="footer-copyright text-center">
            <div class="text">
                <span>
                    © 2020 Copyright:
                    <a href="/"> KEYGAMES.FR </a>
                    <a href="/admin"><i class="fa fa-sign-in"></i></a>
                </span>
                <br>
                <span>
                    Made with ♥ by Nicolas HERMOSILLA & Antonio RAKOTOMALALA
                </span>
            </div>
        </div>
    </footer>

    @yield('extra-js')

</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
</script>

</html>